# Generated by Django 6.0.2 on 2026-02-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
