# Generated by Django 6.0.2 on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_dashboard', '0002_secret_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='is_access_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
