# Generated by Django 6.0.2 on 2026-03-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_dashboard', '0004_secretpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretpolicy',
            name='regex_mode',
            field=models.CharField(choices=[('match', 'Should Match'), ('not_match', 'Should Not Match')], default='match', max_length=20),
        ),
    ]
