# Generated by Django 6.0.2 on 2026-03-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_dashboard', '0005_secretpolicy_regex_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='owner_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='secret',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
