# Generated by Django 6.0.2 on 2026-02-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultconfig',
            name='threshold',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='vaultconfig',
            name='total_shares',
            field=models.IntegerField(default=5),
        ),
    ]
