# Generated by Django 6.0.2 on 2026-02-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_vaultconfig_threshold_vaultconfig_total_shares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vaultconfig',
            name='device_id',
        ),
        migrations.AddField(
            model_name='vaultconfig',
            name='device_public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaultconfig',
            name='threshold',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vaultconfig',
            name='total_shares',
            field=models.IntegerField(),
        ),
    ]
