# Generated by Django 6.0.2 on 2026-02-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_remove_vaultconfig_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultconfig',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
