# Generated by Django 6.0.2 on 2026-02-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_vaultconfig_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultconfig',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='vaultconfig',
            name='device_public_key',
        ),
        migrations.RemoveField(
            model_name='vaultconfig',
            name='threshold',
        ),
        migrations.RemoveField(
            model_name='vaultconfig',
            name='total_shares',
        ),
        migrations.AddField(
            model_name='vaultconfig',
            name='credential_id',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='vaultconfig',
            name='public_key',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='vaultconfig',
            name='sign_count',
            field=models.IntegerField(default=0),
        ),
    ]
