# Generated by Django 6.0.2 on 2026-03-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_remove_vaultconfig_device_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.BinaryField(unique=True)),
                ('public_key', models.BinaryField()),
                ('sign_count', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_devices', to='vault.vaultconfig')),
            ],
        ),
    ]
