# Generated by Django 6.0.2 on 2026-03-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_webauthndevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='webauthndevice',
            name='device_fingerprint',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webauthndevice',
            name='device_label',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='webauthndevice',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='webauthndevice',
            constraint=models.UniqueConstraint(fields=('vault', 'device_fingerprint'), name='unique_webauthn_device_per_vault_fingerprint'),
        ),
    ]
