# Generated by Django 6.0.2 on 2026-03-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_webauthndevice_mobile_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='webauthndevice',
            name='unique_webauthn_device_per_vault_fingerprint',
        ),
    ]
