# Generated by Django 5.2.13 on 2026-04-26 04:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0009_shamir_unseal_refactor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vaultconfig",
            name="is_sealed",
        ),
        migrations.AddField(
            model_name="vaultconfig",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="vaultconfig",
            name="initialized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vaultconfig",
            name="initialized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vaultconfig",
            name="root_token_hash",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="vaultconfig",
            name="sealed",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="secret",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="vaultconfig",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
