# Generated by Django 6.0.3 on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0010_remove_vaultconfig_is_sealed_vaultconfig_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secret",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="vaultconfig",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
