# Generated by Django 5.2.13 on 2026-04-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_emailconfig_google_chat_webhook_encrypted"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailconfig",
            name="microsoft_teams_channel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="emailconfig",
            name="microsoft_teams_webhook_encrypted",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailconfig",
            name="slack_channel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="emailconfig",
            name="slack_webhook_encrypted",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
